HOST: 127.0.0.1
PORT: 8080

SWAGGER_FILE_PATH: swagger/swagger.yaml
ACTIONLOG_DEFAULT_ACTOR: "authen-api"
ACTIONLOG_ENABLED: true
SESSION_COOKIE_NAME: "authen-api"

SECURE_MODE: false

TENANT_MASTER_NAME: MASTER
CLIENT_MASTER_NAME: VCS_MASTER

TOKEN_LEEWAY_TIME: 300              #seconds
TOKEN_EXPIRATION_TIME: 3600         #seconds

SQLALCHEMY_DATABASE_URI: ""
SQLALCHEMY_TRACK_MODIFICATIONS: false

SOCIAL_MONGO_DB : ''
SOCIAL_MONGO_URI : ''